name = "crm"
compatibility_date = "2024-03-20"
main = "server/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "crm-db"
database_id = "20871eab-b731-4683-ad37-309a1319f795"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "crm-attachments"

[ai]
binding = "AI"
